### ISSUE TITLE
Questions related to configurations via CRDs.

### ISSUE THREAD

**Issue by 5hin0bi** [openappsec/openappsec#105]
Hello!

I got multiple questions if you let me, please. Using version 1.1.5 here. (Not connected to the WebUI console). Latest image.

1. Do countryCode based exceptions work if using k8s with CRDs? I've seen the issue resolved, not in my case unfortunatelly.

2. What is the order of the exceptions? E.g. I got a policy that works for all the ingresses defined in my cluster. Since the limitation I define countryCode based rules in separate exception CRD.
```
---
apiVersion: openappsec.io/v1beta1
kind: Policy
metadata:
    name: open-webapp-best-practice-policy
spec:
    default:
        mode: prevent
        practices:
            - webapp-best-practice
        triggers:
            - appsec-special-log-trigger
        custom-response: 403-forbidden
        exceptions:
            - appsec-exception-country-code # drop ES (Spain)
            - appsec-exception-general # accept "wp-(.*)"
```
What happens to one requesting https://example.com/wp-admin from Spain? Would he be dropped or accepted?
Didn't find the explanation for the CRD case on the website, sorry.

3. Today we faced DDoS attack and couldn't do anything with it since country based rules didn't work and there are no CRDs to define DDoS mitigations rules too. :<
I cannot use WebUI since the company security policies.

**Comment by orianelou** [comment]
Hi @5hin0bi, 

1. Yes, country code exceptions should be fixed.
2. Exception order is from strictest (Drop) to less strict (Accept), we're looking into recreating your set-up to check your-use case, could you please confirm those are the same exceptions you used in production?
3. My apologies, we're working on a new CRD version that will include rate limiting, and hope to publish it soon.

Best regards, 

open-appsec team

**Comment by 5hin0bi** [comment]
Hi @orianelou,
1. Thanks for your answer, upgraded to 1.1.6 just in case, still no luck though.
2. Thank you, much clearer now. Yes, we used the same setup last time when faced ddos attack (I've seen most IPs were from Spain according to the MMDB). Now it's gone so I've yet excluded the country based exception from the policy exceptions array.
3. Thank you for your efforts!

**Comment by justsaumit** [comment]
Hi @5hin0bi, are you able to implement GeoIP blocking using CRDs alone? 
We too are currently not in a position to use the WebUI for prod but for testing purpose we were able to make use of it. It worked when we made use of managed mode with the webui and the scripts. but using just plain CRDs creating exception in policy we are not able to achieve the same. Any help?
