### ISSUE TITLE
Attachment configuration resets indefinitely on Kubernetes

### ISSUE THREAD

**Issue by ori-nat** [openappsec/openappsec#11]
Hi,

I followed the [installation guide](https://docs.openappsec.io/getting-started/start-with-kubernetes/install-using-interactive-cli-tool) for Kubernetes on a test server with microk8s installed. The installation went well and the ingress controller is still functional, but it seems there's some issue with the attachment configuration.

The output of `kubectl logs open-appsec-open-appsec-k8s-nginx-ingress-controller-0 -n appsec` shows the same **"Web AppSec Policy Loaded Successfully"** event recurring every ~35 seconds:
```
{"eventTime": "2023-02-01T13:53:53.238","eventName": "Web AppSec Policy Loaded Successfully","eventSeverity": "Low","eventPriority": "Low","eventType": "Event Driven","eventLevel": "Log","eventLogLevel": "info","eventAudience": "Security","eventAudienceTeam": "","eventFrequency": 0,"eventTags": ["Threat Prevention"],"eventSource": {"agentId": "Unknown","eventTraceId": "","eventSpanId": "","issuingEngineVersion": "1.0.0-open-source","serviceName": "HTTP Transaction Handler","serviceId": "1"},"eventData": {"logIndex": 261}}
{"eventTime": "2023-02-01T13:54:27.368","eventName": "Web AppSec Policy Loaded Successfully","eventSeverity": "Low","eventPriority": "Low","eventType": "Event Driven","eventLevel": "Log","eventLogLevel": "info","eventAudience": "Security","eventAudienceTeam": "","eventFrequency": 0,"eventTags": ["Threat Prevention"],"eventSource": {"agentId": "Unknown","eventTraceId": "","eventSpanId": "","issuingEngineVersion": "1.0.0-open-source","serviceName": "HTTP Transaction Handler","serviceId": "1"},"eventData": {"logIndex": 262}}
{"eventTime": "2023-02-01T13:55:02.030","eventName": "Web AppSec Policy Loaded Successfully","eventSeverity": "Low","eventPriority": "Low","eventType": "Event Driven","eventLevel": "Log","eventLogLevel": "info","eventAudience": "Security","eventAudienceTeam": "","eventFrequency": 0,"eventTags": ["Threat Prevention"],"eventSource": {"agentId": "Unknown","eventTraceId": "","eventSpanId": "","issuingEngineVersion": "1.0.0-open-source","serviceName": "HTTP Transaction Handler","serviceId": "1"},"eventData": {"logIndex": 263}}
```
No other events are recorded, even while sending traffic to the ingress controller.

I also checked the controller logs and it seems that the attachment is being reconfigured/reset indefinitely. The log sequence below appears every ~30 seconds.
```
|2023-02-01T13:52:13.151: is_ngx_cp_attachment_disabled@ngx_http_cp_attachment_module.c:243 [uid 1 | pid 739] | Reconfiguring the local NGINX attachment state
|2023-02-01T13:52:13.152: is_static_resource_request@ngx_cp_static_content.c:229 [uid 1 | pid 739] <session id 712> | Cannot determine whether request is for a static resource: static resources' table is not initialized
|2023-02-01T13:52:23.141: is_static_resource_request@ngx_cp_static_content.c:229 [uid 1 | pid 739] <session id 713> | Cannot determine whether request is for a static resource: static resources' table is not initialized
|2023-02-01T13:52:23.143: is_static_resource_request@ngx_cp_static_content.c:229 [uid 1 | pid 739] <session id 714> | Cannot determine whether request is for a static resource: static resources' table is not initialized
|2023-02-01T13:52:33.141: is_static_resource_request@ngx_cp_static_content.c:229 [uid 1 | pid 739] <session id 715> | Cannot determine whether request is for a static resource: static resources' table is not initialized
|2023-02-01T13:52:33.142: is_static_resource_request@ngx_cp_static_content.c:229 [uid 2 | pid 740] <session id 493> | Cannot determine whether request is for a static resource: static resources' table is not initialized
|2023-02-01T13:52:33.145: reset_attachment_config@ngx_cp_utils.c:971 [uid 2 | pid 740] <session id 493> | Resetting attachment configuration
|2023-02-01T13:52:33.145: init_general_config@ngx_cp_utils.c:921 [uid 2 | pid 740] <session id 493> | Successfully loaded configuration. inspection mode: 0, debug level: 2, failure mode: fail-open, fail mode timeout: 50 msec, failure wait mode: fail-open, fail mode wait timeout: 150 msec, sessions per minute limit verdict: Accpet, max sessions per minute: 0, req max processing time: 3000 msec, res max processing time: 3000 msec, registration thread timeout: 100 msec, req header thread timeout: 100 msec, req body thread timeout: 150 msec, res header thread timeout: 100 msec, res body thread timeout: 150 msec, wait thread timeout: 150 msec, static resources path: /dev/shm/static_resources, num of nginx ipc elements: 200, keep alive interval msec: 150000 msec
```
My `ingress.yaml`:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    openappsec.io/policy: open-appsec-best-practice-policy
    nginx.ingress.kubernetes.io/service-upstream: "true"
  labels:
    app: nginx-ingress-microk8s
  name: nginx-ingress-microk8s
  namespace: default
spec:
  ingressClassName: appsec-nginx
  defaultBackend:
    service:
      name: service1
      port:
        number: 80
```

And the sample service it communicates with:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: httpd
          ports:
            - name: http
              containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service1
  type: ClusterIP
```

I'm using the default `open-appsec-policy.yaml` that comes with the installation.

Any ideas what went wrong?

Thanks.

**Comment by WrightNed** [comment]
Hi,

Thank you for letting us know - we are looking into the issue and will update as soon as we know something.

Thanks,
Ned

**Comment by WrightNed** [comment]
Hi,

Just updating that the issue is still under investigation.

Sorry for the long response time,
Ned

**Comment by WrightNed** [comment]
Hi,

We believe we've found the issue and it should be fixed in the next version.

Thanks,
Ned

**Comment by orianelou** [comment]
Hi,

The issue is now solved. 

Thank you for your patience,

Oriane

**Comment by swissbuechi** [comment]
I'm still faceing the same issue.

Kubernetes Cluster running on AKS and open-appsec 1.1.8 deployed via HELM.

**Comment by ksgnextuple** [comment]
Getting very similar logs

**Comment by swissbuechi** [comment]
@WrightNed @orianelou 

Any updates regarding this issue?

Thank you very much.

**Comment by ksgnextuple** [comment]
Have created another ticket for the same, basically the policy.json of the appsec container is not getting updated. It's working when there are less number of ingress resources.
